# Generated by Django 4.1.4 on 2022-12-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extensionusuario',
            name='link_pag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
